//
//  PixelPets.swift
//  NotchPet
//

import SwiftUI

private let catPalette: [Character: Color] = [
    "G": Color(red: 247 / 255, green: 127 / 255, blue: 60 / 255),
    "g": Color(red: 217 / 255, green: 94 / 255, blue: 31 / 255),
    "d": Color(red: 163 / 255, green: 67 / 255, blue: 19 / 255),
    "D": Color(red: 95 / 255, green: 60 / 255, blue: 8 / 255),
    "C": Color(red: 255 / 255, green: 157 / 255, blue: 66 / 255),
    "P": Color(red: 247 / 255, green: 168 / 255, blue: 196 / 255),
    "K": Color(red: 34 / 255, green: 32 / 255, blue: 52 / 255)
]

private let walkingFrames: [[String]] = [
    [
        ".................Gd...",
        ".................GGd..",
        "..................GGd.",
        "..g....g...........Gd.",
        ".gdg..gdg..........Gd.",
        ".gGGGGGdg..........Gd.",
        "GGGGGGGGGg........GGd.",
        "GKGGGGKGGg........Gd..",
        "GGGDGGGGGGg......GGd..",
        "gGDPDGGgGggggGggGGd...",
        "GGGGGGGGGggGGGgGGd....",
        ".GGGGGGGGGGGGgGGd.....",
        "..GGCGGGGGGGGGGGd.....",
        "..GCCCGGGGGGGGGGd.....",
        "..gCCCCGGGGGGGGGGd....",
        "...gCCCGGGCCCCGGGd....",
        "...GgggGGddddddGGd....",
        "...Gg..Gg....gg.Gd....",
        "...gg..Gg....gg.Gd....",
    ],
    [
        "..................Gd..",
        "..................GGd.",
        "...................Gd.",
        "..g....g...........Gd.",
        ".gdg..gdg..........Gd.",
        ".gGGGGGdg..........Gd.",
        "GGGGGGGGGg........GGd.",
        "GKGGGGKGGg........Gd..",
        "GGGDGGGGGGgggGgg.GGd..",
        "gGDPDGGgGggggGggGGd...",
        "GGGGGGGGGggGGGgGGd....",
        ".GGGGGGGGGGGGgGGd.....",
        "..GGCGGGGGGGGGGGd.....",
        "..GCCCGGGGGGGGGGd.....",
        "..gCCCCGGGGGGGGGGd....",
        "...gCCCGGGCCCCGGGd....",
        "...GgggGGddddddGGd....",
        "...Gg..Gg....gg.Gd....",
        "...gg...........Gd....",
    ],
    [
        "....................Gd",
        "...................Gd.",
        "...................Gd.",
        "..g....g...........Gd.",
        ".gdg..gdg..........Gd.",
        ".gGGGGGdg..........Gd.",
        "GGGGGGGGGg........GGd.",
        "GKGGGGKGGg........Gd..",
        "GGGDGGGGGGg......GGd..",
        "gGDPDGGgGggggGggGGd...",
        "GGGGGGGGGggGGGgGGd....",
        ".GGGGGGGGGGGGgGGd.....",
        "..GGCGGGGGGGGGGGd.....",
        "..GCCCGGGGGGGGGGd.....",
        "..gCCCCGGGGGGGGGGd....",
        "...gCCCGGGCCCCGGGd....",
        "...GgggGGddddddGGd....",
        "...Gg..Gg....gg.Gd....",
        "...gg.Gg....gg..Gd....",
    ],
    [
        "..................Gd..",
        "..................GGd.",
        "...................Gd.",
        "..g....g...........Gd.",
        ".gdg..gdg..........Gd.",
        ".gGGGGGdg..........Gd.",
        "GGGGGGGGGg........GGd.",
        "GKGGGGKGGg........Gd..",
        "GGGDGGGGGGgggGgg.GGd..",
        "gGDPDGGgGggggGggGGd...",
        "GGGGGGGGGggGGGgGGd....",
        ".GGGGGGGGGGGGgGGd.....",
        "..GGCGGGGGGGGGGGd.....",
        "..GCCCGGGGGGGGGGd.....",
        "..gCCCCGGGGGGGGGGd....",
        "...gCCCGGGCCCCGGGd....",
        "...GgggGGddddddGGd....",
        "...Gg..Gg....gg.Gd....",
        ".......Gg....gg.G.....",
    ],
    [
        ".................Gd...",
        ".................GGd..",
        "..................GGd.",
        "..g....g...........Gd.",
        ".gdg..gdg..........Gd.",
        ".gGGGGGdg..........Gd.",
        "GGGGGGGGGg........GGd.",
        "GKGGGGKGGg........Gd..",
        "GGGDGGGGGGg......GGd..",
        "gGDPDGGgGggggGggGGd...",
        "GGGGGGGGGggGGGgGGd....",
        ".GGGGGGGGGGGGgGGd.....",
        "..GGCGGGGGGGGGGGd.....",
        "..GCCCGGGGGGGGGGd.....",
        "..gCCCCGGGGGGGGGGd....",
        "...gCCCGGGCCCCGGGd....",
        "...GgggGGddddddGGd....",
        "...Gg..Gg....gg.Gd....",
        "..gg...Gg....gg.Gd....",
    ],
    [
        "................Gd....",
        "................GGd...",
        ".................Gd...",
        "..g....g.........Gd...",
        ".gdg..gdg........Gd...",
        ".gGGGGGdg........Gd...",
        "GGGGGGGGGg......GGd...",
        "GKGGGGKGGg......Gd....",
        "GGGDGGGGGggGgg.GGd....",
        "gGDPDGGgGggGggGGd.....",
        "GGGGGGGGGGGGgGGd......",
        ".GGGGGGGGGGgGGd.......",
        "..GGCGGGGGGGGGd.......",
        "..GCCCGGGGGGGGd.......",
        "..gCCCCGGGGGGGGd......",
        "...gCCCGGCCCGGGd......",
        "...GgggGGddddGGd......",
        "...Gg..Gg..gg.Gd......",
        ".......Gg..gg.G.......",
    ],
    [
        "................Gd....",
        "................GGd...",
        "..g....g.........Gd...",
        ".gdg..gdg........Gd...",
        ".gGGGGGdg........Gd...",
        "GGGGGGGGGg.......Gd...",
        "GKGGGGKGGg......GGd...",
        "GGGDGGGGGg......Gd....",
        "gGDPDGGgGggGgg.GGd....",
        "GGGGGGGGGGgGggGGd.....",
        ".GGGGGGGGGGGgGGd......",
        "..gGGGGGGGGgGGd.......",
        "..GGCGGGGGGGGGd.......",
        "..GCCCGGGGGGGGd.......",
        "..gCCCCGGGGGGGGd......",
        "...gCCCGGCCCGGGd......",
        "...GgggGGddddGGd......",
        "...Gg..Gg..gg.Gd......",
        ".......Gg..gg.G.......",
    ],
    [
        ".............Gd.......",
        ".............GGd......",
        "..............Gd......",
        "..g....g......Gd......",
        ".gdg..gdg.....Gd......",
        ".gGGGGGdg.....Gd......",
        "GGGGGGGGGg...GGd......",
        "GKGGGGKGGg...Gd.......",
        "GGGDGGGgGgg.GGd.......",
        "gGDPDGGgGggGGd........",
        "GGGGGGGGGgGGd.........",
        ".GGGGGGGgGGd..........",
        "..GGCGGGGGGd..........",
        "..GCCCGGGGGd..........",
        "..gCCCCGGGGGd.........",
        "...gCCCCCGGGd.........",
        "...GgggGgdGGd.........",
        "...Gg..Ggd.Gd.........",
        "...Gg..Ggd.Gd.........",
    ],
    [
        ".dG...................",
        "dGG...................",
        "dG....................",
        "dG.....g....g.........",
        "dG....gdg..gdg........",
        "dG....gdGGGGGg........",
        "dGG..gGGGGGGGGG.......",
        ".dG..gGGKGGGGKG.......",
        ".dGGggGgGGGDGGG.......",
        "..dGGgGgGGDPDGg.......",
        "...dGgGGGGGGGGG.......",
        "...dGGgGGGGGGG........",
        "...dGGGGGGCGG.........",
        "...dGGGGGCCCG.........",
        "..dGGGGGCCCCg.........",
        "..dGGGCCCCCg..........",
        "..dGGdgGgggG..........",
        "..dG.dgG..gG..........",
        "..dG.dgG..gG..........",
    ],
    [
        ".dG...................",
        "dGG...................",
        "dG....................",
        "dG.........g....g.....",
        "dG........gdg..gdg....",
        "dG........gdGGGGGg....",
        "dGG......gGGGGGGGGG...",
        ".dG......gGGKGGGGKG...",
        ".dGG.ggGggGGGGGDGGG...",
        "..dGGggGggGgGGDPDGg...",
        "...dGGgGGGGGGGGGGGG...",
        "....dGGgGGGGGGGGGG....",
        "....dGGGGGGGGGCGG.....",
        "....dGGGGGGGGCCCG.....",
        "...dGGGGGGGGCCCCg.....",
        "...dGGGCCCGGCCCg......",
        "...dGGddddGGgggG......",
        "...dG.gg..gG..gG......",
        "....G.gg..gG..........",
    ],
    [
        ".dG...................",
        "dGG...................",
        "dG....................",
        "dG...........g....g...",
        "dG..........gdg..gdg..",
        "dG..........gdGGGGGg..",
        "dGG........gGGGGGGGGG.",
        ".dG........gGGKGGGGKG.",
        ".dGG.ggGgggGGGGGGDGGG.",
        "..dGGggGggggGgGGDPDGg.",
        "...dGGgGGGggGGGGGGGGG.",
        "....dGGgGGGGGGGGGGGG..",
        "....dGGGGGGGGGGGCGG...",
        "....dGGGGGGGGGGCCCG...",
        "...dGGGGGGGGGGCCCCg...",
        "...dGGGCCCCGGGCCCg....",
        "...dGGddddddGGgggG....",
        "...dG.gg....gG..gG....",
        "...dG...........gg....",
    ],
    [
        "dG....................",
        ".dG...................",
        ".dG...................",
        ".dG...........g....g..",
        ".dG..........gdg..gdg.",
        ".dG..........gdGGGGGg.",
        ".dGG........gGGGGGGGGG",
        "..dG........gGGKGGGGKG",
        "..dGG......gGGGGGGDGGG",
        "...dGGggGggggGgGGDPDGg",
        "....dGGgGGGggGGGGGGGGG",
        ".....dGGgGGGGGGGGGGGG.",
        ".....dGGGGGGGGGGGCGG..",
        ".....dGGGGGGGGGGCCCG..",
        "....dGGGGGGGGGGCCCCg..",
        "....dGGGCCCCGGGCCCg...",
        "....dGGddddddGGgggG...",
        "....dG.gg....gG..gG...",
        "....dG..gg....gG.gg...",
    ],
    [
        ".dG...................",
        "dGG...................",
        "dG....................",
        "dG...........g....g...",
        "dG..........gdg..gdg..",
        "dG..........gdGGGGGg..",
        "dGG........gGGGGGGGGG.",
        ".dG........gGGKGGGGKG.",
        ".dGG.ggGgggGGGGGGDGGG.",
        "..dGGggGggggGgGGDPDGg.",
        "...dGGgGGGggGGGGGGGGG.",
        "....dGGgGGGGGGGGGGGG..",
        "....dGGGGGGGGGGGCGG...",
        "....dGGGGGGGGGGCCCG...",
        "...dGGGGGGGGGGCCCCg...",
        "...dGGGCCCCGGGCCCg....",
        "...dGGddddddGGgggG....",
        "...dG.gg....gG..gG....",
        "....G.gg....gG........",
    ],
    [
        "..dG..................",
        ".dGG..................",
        "dGG...................",
        "dG...........g....g...",
        "dG..........gdg..gdg..",
        "dG..........gdGGGGGg..",
        "dGG........gGGGGGGGGG.",
        ".dG........gGGKGGGGKG.",
        ".dGG......gGGGGGGDGGG.",
        "..dGGggGggggGgGGDPDGg.",
        "...dGGgGGGggGGGGGGGGG.",
        "....dGGgGGGGGGGGGGGG..",
        "....dGGGGGGGGGGGCGG...",
        "....dGGGGGGGGGGCCCG...",
        "...dGGGGGGGGGGCCCCg...",
        "...dGGGCCCCGGGCCCg....",
        "...dGGddddddGGgggG....",
        "...dG.gg....gG..gG....",
        "...dG.gg....gG...gg...",
    ],
    [
        ".dG...................",
        "dGG...................",
        "dG.........g....g.....",
        "dG........gdg..gdg....",
        "dG........gdGGGGGg....",
        "dG.......gGGGGGGGGG...",
        "dGG......gGGKGGGGKG...",
        ".dG......gGGGGGDGGG...",
        ".dGG.ggGggGgGGDPDGg...",
        "..dGGggGgGGGGGGGGGG...",
        "...dGGgGGGGGGGGGGG....",
        "....dGGgGGGGGGGGg.....",
        "....dGGGGGGGGGCGG.....",
        "....dGGGGGGGGCCCG.....",
        "...dGGGGGGGGCCCCg.....",
        "...dGGGCCCGGCCCg......",
        "...dGGddddGGgggG......",
        "...dG.gg..gG..gG......",
        "....G.gg..gG..........",
    ],
    [
        ".dG...................",
        "dGG...................",
        "dG....................",
        "dG......g....g........",
        "dG.....gdg..gdg.......",
        "dG.....gdGGGGGg.......",
        "dGG...gGGGGGGGGG......",
        ".dG...gGGKGGGGKG......",
        ".dGG.ggGgGGGDGGG......",
        "..dGGggGgGGDPDGg......",
        "...dGGgGGGGGGGGG......",
        "....dGGgGGGGGGG.......",
        "....dGGGGGGCGG........",
        "....dGGGGGCCCG........",
        "...dGGGGGCCCCg........",
        "...dGGGCCCCCg.........",
        "...dGGdgGgggG.........",
        "...dG.dgG..gG.........",
        "...dG.dgG..gG.........",
    ],
    [
        "............Gd........",
        "............GGd.......",
        ".............Gd.......",
        "..g....g.....Gd.......",
        ".gdg..gdg....Gd.......",
        ".gGGGGGdg....Gd.......",
        "GGGGGGGGGg..GGd.......",
        "GKGGGGKGGg..Gd........",
        "GGGDGGGgGggGGd........",
        "gGDPDGGgGgGGd.........",
        "GGGGGGGGGgGd..........",
        ".GGGGGGGgGGd..........",
        "..GGCGGGGGGd..........",
        "..GCCCGGGGGd..........",
        "..gCCCCGGGGGd.........",
        "...gCCCCCGGGd.........",
        "...GgggGgdGGd.........",
        "...Gg..Ggd.Gd.........",
        "...Gg..Ggd.Gd.........",
    ],
]

private let sleepingFrames: [[String]] = [
    [
        ".........................",
        ".........................",
        ".........................",
        "..g....g.................",
        ".gdg..gdg................",
        ".gGGGGGdg.GgggGg.........",
        "GGGGGGGGGgGgggGggGG......",
        "GdGGGGdGGgGgGGGgGdGG.....",
        "GGGDGGGGGGGgGGgGGddGG....",
        "gGDPDGGgGgGGGGGGGd.dGG...",
        "GGGGGGGGGgGGGGGGGd..dG...",
        ".gggGggGGGGGGGGGGGd.dG...",
        "..GGgCCCGGGCCCCGGGd.dG...",
        ".gggGgddGGddddddGGddG....",
    ],
    [
        "...g......g..............",
        ".........................",
        "g............g...........",
        ".....g....g..............",
        "....gdg..gdg.............",
        "....gGGGGGdg.............",
        "...GGGGGGGGGgGgggGggGG...",
        "...GdGGGGdGGgGgGGGgGdGG..",
        "...GGGDGGGGGGGgGGgGGddGG.",
        "...gGDPDGGgGgGGGGGGGd.dGG",
        "...GGGGGGGGGgGGGGGGGd..dG",
        "....gggGggGGGGGGGGGGGd.dG",
        ".....GGgCCCGGGCCCCGGGd.dG",
        "....gggGgddGGddddddGGddG.",
    ],
]

enum CatPixelArtMetrics {
    static let walkingFrameWidth = walkingFrames.first?.first?.count ?? 0
    static let sleepingFrameWidth = sleepingFrames.first?.first?.count ?? 0
    static let walkingFrameCount = walkingFrames.count
    static let sleepingFrameCount = sleepingFrames.count
}

struct PixelSpriteView: View {
    let rows: [String]
    let pixelSize: CGFloat
    var mirrored: Bool = false

    var body: some View {
        let width = CGFloat(rows.first?.count ?? 0) * pixelSize
        let height = CGFloat(rows.count) * pixelSize

        Canvas { context, _ in
            for (y, row) in rows.enumerated() {
                for (x, token) in row.enumerated() {
                    guard let color = catPalette[token] else { continue }
                    let rect = CGRect(
                        x: CGFloat(x) * pixelSize,
                        y: CGFloat(y) * pixelSize,
                        width: pixelSize,
                        height: pixelSize
                    )
                    context.fill(Path(rect), with: .color(color))
                }
            }
        }
        .frame(width: width, height: height)
        .scaleEffect(x: mirrored ? -1 : 1, y: 1, anchor: .center)
    }
}

struct CatPixelArt: View {
    let isSleeping: Bool
    let frame: Int
    let scale: CGFloat
    let mirrored: Bool

    var body: some View {
        PixelSpriteView(
            rows: currentFrame,
            pixelSize: scale,
            mirrored: mirrored
        )
    }

    private var currentFrame: [String] {
        if isSleeping {
            return sleepingFrames[frame % sleepingFrames.count]
        }
        return walkingFrames[frame % walkingFrames.count]
    }
}
